### ISSUE TITLE
No error but empty plot

### ISSUE THREAD

**Issue by PietroD** [harbourlab/PieParty#3]
Hi 
Thanks for the tool, looks very interesting.
But I am obtaining an empty plot file and that's it.
It changes size when I increase resolution, but is always empty.

I tried on macOS Catalina and Ubuntu, both with using Python 3, 3.6.6 and 3.9.1

Thanks

**Comment by harbourlab** [comment]
Hi! Can you please send the exact command you used to run pie party? Also, what size does the output svg file have? what program do you use to open the svg? Can you try a different one? Happy to help! Let me know :)

Sent from my iPhone

On Jan 18, 2021, at 11:04 AM, PietroD <notifications@github.com> wrote:

﻿
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


Hi
Thanks for the tool, looks very interesting.
But I am obtaining an empty plot file and that's it.
It changes size when I increase resolution, but is always empty.
Thanks

**Comment by PietroD** [comment]
`python3 PieParty.py -g gexp_trt48h_filtered.csv -c cell_coordinates_trt48h_filtered.csv -l classical.csv`

I get no svg output. Only .png. I tried Preview and Chrome on MacOS. The size is around 500KB.
Thanks

**Comment by harbourlab** [comment]
Thanks. Could you also please provide the files you used? The complete ones will be to big, but maybe you could use "head -50" or so so that i can check the structure of them. THanks!

**Comment by PietroD** [comment]
Here you are

[archive.zip](https://github.com/harbourlab/PieParty/files/5851142/archive.zip)

**Comment by harbourlab** [comment]
I checked your files and they seem fine. The script will immediatelly make output .png files when it starts to run, however, these will be empty until the script has finished running. Depending on your dataset this might take a while (24 hours for 50000 cells approx). Could it be that the script was not done yet? Else, if you can share your entire dataset e.g. with Dropbox I would be happy to run it and check.

**Comment by PietroD** [comment]
Found the problem! The script was terminating with a message:

`The gene "xxx" was not found in expression dataset`

And I thought it was just a warning.

But then, with a fake geneset file with very few genes that I know exist in the expression table, I get a new error:

```
Traceback (most recent call last):
  File "PieParty.py", line 320, in <module>
    plotpie(i[0], i[1], i[2])
  File "PieParty.py", line 49, in plotpie
    plt.pie(sizes, colors=colors)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3322, in pie
    ax = gca()
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 984, in gca
    return gcf().gca(**kwargs)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/home/pdelfino/Programs/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```

**Comment by harbourlab** [comment]
This is valuable feedback. I guess after the error the output file should be deleted, I will add this to the script soon. I'm not sure what is causing your error, the script is working fine for me. I will upload an example dataset today, you can use to test!

**Comment by harbourlab** [comment]
I have added an example dataset and description. The set should run in 5 minutes. You can use this to test. Let me know!
